name: post_pal
description: "A project for reading other user's posts or writing stories, new knowledge which may be valuable."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

