// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKM4izf4yKQb2Q6VxvLGlL3JWckjWbhmM',
    appId: '1:899471160793:web:f41faaeddf41d7fc8b15c8',
    messagingSenderId: '899471160793',
    projectId: 'postpal-project',
    authDomain: 'postpal-project.firebaseapp.com',
    storageBucket: 'postpal-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHUw0jLKVpxvkyIHviFnXMF3KE-Je_kvU',
    appId: '1:899471160793:android:60a707d664f3ce9e8b15c8',
    messagingSenderId: '899471160793',
    projectId: 'postpal-project',
    storageBucket: 'postpal-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvTQ5KTxuaDlpnRrvPE8KyeYGmy7XiBf8',
    appId: '1:899471160793:ios:f495e274df8518118b15c8',
    messagingSenderId: '899471160793',
    projectId: 'postpal-project',
    storageBucket: 'postpal-project.appspot.com',
    iosBundleId: 'com.pdp.uz.postApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvTQ5KTxuaDlpnRrvPE8KyeYGmy7XiBf8',
    appId: '1:899471160793:ios:c9f267f1a53a058e8b15c8',
    messagingSenderId: '899471160793',
    projectId: 'postpal-project',
    storageBucket: 'postpal-project.appspot.com',
    iosBundleId: 'com.pdp.uz.postApp.RunnerTests',
  );
}
